// C:\nifdu\src\api_codegen.cpp
#include "api_codegen.hpp"

#include <sstream>
#include <string>
#include <ctime>

using namespace std;

namespace {

// Tiny helper to escape JSON string values without pulling in a JSON lib.
std::string json_escape(const std::string& s) {
    std::string out;
    out.reserve(s.size() + 16);
    for (char c : s) {
        switch (c) {
        case '\"': out += "\\\""; break;
        case '\\': out += "\\\\"; break;
        case '\b': out += "\\b";  break;
        case '\f': out += "\\f";  break;
        case '\n': out += "\\n";  break;
        case '\r': out += "\\r";  break;
        case '\t': out += "\\t";  break;
        default:
            if (static_cast<unsigned char>(c) < 0x20) {
                char buf[7];
                snprintf(buf, sizeof(buf), "\\u%04x", c);
                out += buf;
            } else {
                out += c;
            }
        }
    }
    return out;
}

std::string now_iso8601() {
    std::time_t t = std::time(nullptr);
    std::tm tm{};
#if defined(_WIN32)
    gmtime_s(&tm, &t);
#else
    gmtime_r(&t, &tm);
#endif
    char buf[32];
    std::strftime(buf, sizeof(buf), "%Y-%m-%dT%H:%M:%SZ", &tm);
    return std::string(buf);
}

// Add CORS headers for browser calls from http://127.0.0.1
void apply_cors(httplib::Response& res) {
    // For local dev, wildcard is fine. If you prefer, replace "*" with "http://127.0.0.1".
    res.set_header("Access-Control-Allow-Origin", "*");
    res.set_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
    res.set_header("Access-Control-Allow-Headers", "Content-Type, Accept");
    res.set_header("Access-Control-Max-Age", "600");
}

} // namespace

namespace nifdu::codegen {

void register_routes(httplib::Server& svr) {
    // ---------------------------------------------------------------
    // OPTIONS /api/codegen   (CORS preflight)
    // ---------------------------------------------------------------
    svr.Options("/api/codegen", [](const httplib::Request& req, httplib::Response& res) {
        apply_cors(res);
        res.status = 204; // No Content
    });

    // ---------------------------------------------------------------
    // GET /api/codegen
    // Simple status/introspection endpoint so tools can verify that
    // the special handler is active.
    // ---------------------------------------------------------------
    svr.Get("/api/codegen", [](const httplib::Request& req, httplib::Response& res) {
        std::ostringstream oss;
        oss << "{\n";
        oss << "  \"status\": \"ok\",\n";
        oss << "  \"stub\": true,\n";
        oss << "  \"endpoint\": \"/api/codegen\",\n";
        oss << "  \"method\": \"GET\",\n";
        oss << "  \"engine\": \"nifdu_codegen_v0\",\n";
        oss << "  \"note\": \"Use POST /api/codegen with JSON for full plan.\",\n";
        oss << "  \"timestamp\": \"" << json_escape(now_iso8601()) << "\"\n";
        oss << "}\n";

        res.set_content(oss.str(), "application/json");
        apply_cors(res);
    });

    // ---------------------------------------------------------------
    // POST /api/codegen
    //
    // v0 behavior:
    //  - Echo raw request body into request_prompt field.
    //  - Return simple files[] array (C++ + HTML placeholders).
    // ---------------------------------------------------------------
    svr.Post("/api/codegen", [](const httplib::Request& req, httplib::Response& res) {
        const std::string raw_body = req.body;

        std::ostringstream oss;
        oss << "{\n";
        oss << "  \"status\": \"ok\",\n";
        oss << "  \"endpoint\": \"/api/codegen\",\n";
        oss << "  \"engine\": \"nifdu_codegen_v0\",\n";
        oss << "  \"request_prompt\": \"" << json_escape(raw_body) << "\",\n";
        oss << "  \"note\": \"Codegen stub is running live on Port 8000.\",\n";

        // Minimal fake file list (what Agent 3 will put into localStorage)
        oss << "  \"files\": [\n";
        oss << "    {\n";
        oss << "      \"path\": \"app/todo/main.cpp\",\n";
        oss << "      \"language\": \"cpp\",\n";
        oss << "      \"content\": \"// Placeholder code generated by v0 stub.\\n"
               "#include <iostream>\\n"
               "int main(){ std::cout << \\\"Hello from NIFDU codegen v0!\\\\n\\\"; }\\n\"\n";
        oss << "    },\n";
        oss << "    {\n";
        oss << "      \"path\": \"app/todo/index.html\",\n";
        oss << "      \"language\": \"html\",\n";
        oss << "      \"content\": \"<!DOCTYPE html>\\n"
               "<html><head><meta charset=\\\\\"utf-8\\\\\">"
               "<title>NIFDU TODO DEMO</title></head>"
               "<body><h1>NIFDU TODO DEMO</h1>"
               "<p>Generated by /api/codegen v0.</p></body></html>\"\n";
        oss << "    }\n";
        oss << "  ]\n";
        oss << "}\n";

        res.set_content(oss.str(), "application/json");
        apply_cors(res);
    });
}

} // namespace nifdu::codegen
