#include <iostream>
#include <thread>
#include <chrono>

// Include the header generated by the One-Shot setup
#include "../ops/nifdu_av.h" 

int main() {
    std::cout << "=== NIFDU C++ AV TRIGGER TEST ===" << std::endl;
    
    // Test 1: Simple Bounce
    std::cout << "[CPP] Triggering 'Bounce'..." << std::endl;
    trigger_av_render("bounce the cat");
    
    std::this_thread::sleep_for(std::chrono::seconds(2));

    // Test 2: Complex Prompt
    std::cout << "[CPP] Triggering 'Seizure'..." << std::endl;
    trigger_av_render("the cat is having a violent seizure");

    std::cout << "[CPP] Jobs dispatched. Check your PowerShell Service window!" << std::endl;
    return 0;
}
