# === NIFDU: UI PORT GOVERNOR INJECTION (auto) ===
$__NIFDU_OPS = "C:\nifdu\ops"
$__NIFDU_FREE = Join-Path $__NIFDU_OPS "free_port.ps1"
if(Test-Path $__NIFDU_FREE){
  try{
    powershell -ExecutionPolicy Bypass -File $__NIFDU_FREE -Port 3000 | Out-Host
  } catch {
    Write-Host ("[WARN] free_port.ps1 failed: " + $_.Exception.Message)
  }
}
$env:PORT = "3000"
# === END NIFDU INJECTION ===
# ==============================================
# C:\nifdu\ops\nifdu_sophyane_make_studio.ps1
# SOPHYANE — MAKE /studio PAGE (CLEAN)
# ==============================================
# Responsibilities:
#   - Ensure Sophyane app root exists
#   - Create/overwrite app/studio/page.tsx
#   - Print nice status via Say()
# ==============================================

param()

$ErrorActionPreference = "Stop"

function Say {
    param(
        [string]$Text,
        [string]$Color = "Gray"
    )
    try {
        $valid = [enum]::GetNames([System.ConsoleColor])
        if ($valid -notcontains $Color) {
            $Color = "Gray"
        }
        Write-Host $Text -ForegroundColor $Color
    } catch {
        Write-Host $Text
    }
}

# ------------------------------
# 1) Define app paths
# ------------------------------
$appRoot   = "C:\nifdu\src\apps\sophyane_live"
$studioDir = Join-Path $appRoot "app\studio"
$pagePath  = Join-Path $studioDir "page.tsx"

Say "`n=== SOPHYANE — MAKE /studio PAGE (CLEAN) ===`n" "Yellow"
Say ("App root: {0}" -f $appRoot) "Cyan"

if (-not (Test-Path $appRoot)) {
    Say ("❌ App root not found: {0}" -f $appRoot) "Red"
    throw "App root not found: $appRoot"
}

if (-not (Test-Path $studioDir)) {
    Say ("Creating directory: {0}" -f $studioDir) "DarkCyan"
    New-Item -ItemType Directory -Path $studioDir -Force | Out-Null
}
# ------------------------------
# 2) Build /app/studio/page.tsx content
#    (no here-strings, line-by-line)
# ------------------------------
$pageLines = @()

$pageLines += '"use client";'
$pageLines += ''
$pageLines += 'import React from "react";'
$pageLines += ''
$pageLines += 'export default function StudioPage() {'
$pageLines += '  return ('
$pageLines += '    <main className="min-h-screen bg-slate-950 text-slate-100 flex flex-col items-center justify-center">'
$pageLines += '      <div className="max-w-2xl px-6 py-8 border border-slate-800 rounded-2xl bg-slate-900/60 shadow-lg">'
$pageLines += '        <h1 className="text-3xl font-semibold text-emerald-400 mb-4">'
$pageLines += '          Sophyane Studio'
$pageLines += '        </h1>'
$pageLines += '        <p className="text-slate-300 mb-4">'
$pageLines += '          This page was generated by NIFDU Agent 3.'
$pageLines += '        </p>'
$pageLines += '        <p className="text-slate-400 text-sm">'
$pageLines += '          Wire this route into your vibe coding loop and start shipping full'
$pageLines += '          products from a single monolith.'
$pageLines += '        </p>'
$pageLines += '      </div>'
$pageLines += '    </main>'
$pageLines += '  );'
$pageLines += '}'

$pageContent = $pageLines -join "`r`n"
# ------------------------------
# 3) Write file + dev hints
# ------------------------------
Say ("Writing: {0}" -f $pagePath) "Cyan"
Set-Content -Path $pagePath -Value $pageContent -Encoding UTF8
Say "✅ Wrote /studio page successfully." "Green"

Say "`nNow start or restart your node node_modules\next\dist\bin\node node_modules\next\dist\bin\next dev server with:" "Yellow"
Write-Host '  cd C:\nifdu\src\apps\sophyane_live' -ForegroundColor DarkGray
Write-Host '  $env:PORT = 3001' -ForegroundColor DarkGray
Write-Host '  node node_modules\next\dist\bin\node node_modules\next\dist\bin\node node_modules\next\dist\bin\next dev' -ForegroundColor DarkGray

