param(
    [string]$Project = "react_todo_tailwind_full"
)

$ErrorActionPreference = "Stop"

function Say {
    param([string]$m,[string]$c="Gray")
    try {
        $valid = [enum]::GetNames([System.ConsoleColor])
        if ($valid -notcontains $c) { $c = "Gray" }
        $old = [Console]::ForegroundColor
        [Console]::ForegroundColor = $c
        Write-Host $m
        [Console]::ForegroundColor = $old
    } catch {
        Write-Host $m
    }
}

$AppDir  = "C:\nifdu\src\apps\$Project"
$PkgPath = Join-Path $AppDir "package.json"

Say "`n=== NIFDU REACT TODO VITE FIXER ===`n" "Cyan"
Say ("Project : {0}" -f $Project) "Gray"
Say ("AppDir  : {0}" -f $AppDir)  "Gray"

if (!(Test-Path $AppDir -PathType Container)) {
    Say "[FATAL] AppDir not found." "Red"
    exit 1
}
if (!(Test-Path $PkgPath)) {
    Say "[FATAL] package.json not found." "Red"
    exit 1
}

# 1) Patch package.json: scripts + devDependencies
Say "[1] Patching package.json (scripts + devDependencies)..." "Cyan"

$jsonText = Get-Content $PkgPath -Raw
$pkg      = $jsonText | ConvertFrom-Json

if (-not $pkg.scripts) {
    $pkg | Add-Member -NotePropertyName scripts -NotePropertyValue @{} -Force
}
if (-not $pkg.devDependencies) {
    $pkg | Add-Member -NotePropertyName devDependencies -NotePropertyValue @{} -Force
}

# Ensure dev/build/preview scripts
$pkg.scripts.dev     = "vite"
$pkg.scripts.build   = "vite build"
$pkg.scripts.preview = "vite preview"

# Ensure vite + @vitejs/plugin-react are present in devDependencies
if (-not $pkg.devDependencies.vite) {
    $pkg.devDependencies | Add-Member -NotePropertyName "vite" -NotePropertyValue "^5.0.0" -Force
}
if (-not $pkg.devDependencies.'@vitejs/plugin-react') {
    $pkg.devDependencies | Add-Member -NotePropertyName "@vitejs/plugin-react" -NotePropertyValue "^4.0.0" -Force
}

# Write back as UTF-8 (no BOM)
$newJson = $pkg | ConvertTo-Json -Depth 10
$enc     = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($PkgPath, $newJson, $enc)

Say (" -> Patched: {0}" -f $PkgPath) "Green"

# 2) Ensure landing page under webroot
Say "[2] Ensuring webroot landing page..." "Cyan"

$WwwAppDir = "C:\webroot\nifdu.com\www\apps\$Project"
$Landing   = Join-Path $WwwAppDir "index.html"

New-Item -ItemType Directory -Path $WwwAppDir -Force | Out-Null

$landingHtml = @"
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>NIFDU React Todo (Tailwind)</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body {
      margin: 0;
      min-height: 100vh;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #020617;
      color: #e5e7eb;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 24px;
    }
    .card {
      background: #020617;
      border-radius: 16px;
      border: 1px solid #1f2937;
      box-shadow: 0 20px 45px rgba(0,0,0,0.6);
      max-width: 560px;
      width: 100%;
      padding: 24px 24px 20px;
    }
    h1 {
      margin: 0 0 8px;
      font-size: 1.5rem;
      color: #22c55e;
    }
    p {
      margin: 4px 0;
      color: #9ca3af;
      line-height: 1.5;
    }
    code {
      background: #030712;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 0.85rem;
    }
    a {
      color: #38bdf8;
      text-decoration: none;
      font-weight: 500;
    }
    a:hover {
      text-decoration: underline;
    }
    .badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      font-size: 0.75rem;
      padding: 4px 8px;
      border-radius: 999px;
      background: rgba(34,197,94,0.12);
      color: #bbf7d0;
      border: 1px solid rgba(34,197,94,0.3);
      margin-bottom: 8px;
    }
    .ball {
      width: 7px;
      height: 7px;
      border-radius: 999px;
      background: #22c55e;
      box-shadow: 0 0 10px #22c55e;
    }
    .steps {
      margin-top: 14px;
      padding-left: 18px;
      font-size: 0.9rem;
      color: #d1d5db;
    }
    .steps li {
      margin-bottom: 4px;
    }
  </style>
</head>
<body>
  <main class="card">
    <div class="badge">
      <span class="ball"></span>
      <span>NIFDU Agent 3 • React + Vite + Tailwind</span>
    </div>
    <h1>NIFDU React Todo App</h1>
    <p>This project was generated by <code>/api/codegen</code> using the NIFDU Agent 3 React stack.</p>
    <p style="margin-top:10px;">To run the live dev server on this machine:</p>
    <ol class="steps">
      <li>Open a PowerShell window.</li>
      <li>Run: <code>cd C:\nifdu\src\apps\$Project</code></li>
      <li>Run: <code>npm install</code> (first time only)</li>
      <li>Run: <code>npm run dev</code></li>
    </ol>
    <p style="margin-top:8px;">
      Once running, open <a href="http://localhost:5173/" target="_blank">http://localhost:5173/</a>
      (or whatever port Vite shows in the console).
    </p>
    <p style="margin-top:10px;font-size:0.8rem;color:#6b7280;">
      This static page is served by <code>nifdu.exe</code> from
      <code>C:\webroot\nifdu.com\www\apps\$Project\index.html</code>.
    </p>
  </main>
</body>
</html>
"@

Set-Content -Path $Landing -Value $landingHtml -Encoding UTF8
Say (" -> Landing page: {0}" -f $Landing) "Green"

# 3) Run npm install + npm run dev
Say "[3] Running npm install + npm run dev..." "Cyan"

Push-Location $AppDir
npm install
npm run dev
Pop-Location
